<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>MicMute.App</StartupObject>
    <RootNamespace>MicMute</RootNamespace>
    <AssemblyName>MicMute</AssemblyName>

    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Compile Remove=".artifacts/**/*.cs" />
    <Compile Remove=".tools/**/*.cs" />
    <EmbeddedResource Include="App.xaml" LogicalName="MicMute.App.xaml" />
    <EmbeddedResource Include="MainWindow.xaml" LogicalName="MicMute.MainWindow.xaml" />
    <EmbeddedResource Include="OsdWindow.xaml" LogicalName="MicMute.OsdWindow.xaml" />
    <EmbeddedResource Include="app.ico" LogicalName="MicMute.app.ico" />
    <Content Include="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
