<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <StartupObject>MicMute.Tests.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../MicMute.csproj" />
  </ItemGroup>
</Project>
